/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package projecttemplate.utilities;

import projecttemplate.list.LinkedList;

/** A utility class for string functions. */
public class StringUtils {
  public static String join(LinkedList source) {
    return JoinUtils.join(source);
  }

  public static LinkedList split(String source) {
    return SplitUtils.split(source);
  }
}
