/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package projecttemplate.app;

import static projecttemplate.app.MessageUtils.getMessage;
import static projecttemplate.utilities.StringUtils.join;
import static projecttemplate.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;
import projecttemplate.list.LinkedList;

/** The main app. */
public class App {

  /**
   * The main entrypoint function.
   *
   * @param args the CLI arguments.
   */
  public static void main(String[] args) {
    LinkedList tokens;
    tokens = split(getMessage());
    String result = join(tokens);
    System.out.println(WordUtils.capitalize(result));
  }
}
