name: Basic validation

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-22.04' ]
        java: [ '19' ]
        distribution: [ 'temurin' ]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Install Gradle
        run: |
          # Gradle is downloaded and installed automatically
          ./gradlew --help
      - name: Code Format
        run: ./gradlew --no-daemon spotlessCheck
      - name: Spot bugs
        run: ./gradlew --no-daemon spotbugsMain spotbugsTest
      - name: Run Tests
        run: ./gradlew --no-daemon test
